"""Initial database schema with all tables

Revision ID: b81e7a91fd55
Revises: 
Create Date: 2025-12-31 23:14:59.870311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81e7a91fd55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False, comment='企業ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='企業名'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='住所'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='電話番号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False, comment='サービスID'),
    sa.Column('service_code', sa.String(length=100), nullable=False, comment='サービスコード'),
    sa.Column('service_name', sa.String(length=255), nullable=False, comment='サービス名'),
    sa.Column('description', sa.Text(), nullable=True, comment='サービス説明'),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='基本料金'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='提供中か'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_service_code'), 'services', ['service_code'], unique=True)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False, comment='支店ID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='所属企業ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='支店名'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='住所'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='電話番号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_table('company_service_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False, comment='契約ID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='企業ID'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='サービスID'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='契約状態（active/suspended/cancelled）'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='契約開始日'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='契約終了日'),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='月額料金（企業別カスタム料金）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_service_subscriptions_company_id'), 'company_service_subscriptions', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_service_subscriptions_id'), 'company_service_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_company_service_subscriptions_service_id'), 'company_service_subscriptions', ['service_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='所属企業ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='氏名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='メールアドレス'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='パスワードハッシュ'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='役割（営業/上長など）'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='役職'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False, comment='顧客ID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='所属企業ID'),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True, comment='担当営業ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='顧客名'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='会社名'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='住所'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='電話番号'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='メールアドレス'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備考'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_assigned_user_id'), 'customers', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False, comment='日報ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='作成者ID'),
    sa.Column('report_date', sa.Date(), nullable=False, comment='報告日'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reports_id'), 'daily_reports', ['id'], unique=False)
    op.create_index(op.f('ix_daily_reports_report_date'), 'daily_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_daily_reports_user_id'), 'daily_reports', ['user_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False, comment='部署ID'),
    sa.Column('branch_id', sa.Integer(), nullable=False, comment='所属支店ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='部署名'),
    sa.Column('description', sa.Text(), nullable=True, comment='説明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_branch_id'), 'departments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('service_subscription_history',
    sa.Column('id', sa.Integer(), nullable=False, comment='履歴ID'),
    sa.Column('subscription_id', sa.Integer(), nullable=False, comment='契約ID'),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True, comment='変更者ID'),
    sa.Column('change_type', sa.String(length=50), nullable=False, comment='変更種別（create/update/delete）'),
    sa.Column('old_status', sa.String(length=50), nullable=True, comment='変更前の契約状態'),
    sa.Column('new_status', sa.String(length=50), nullable=True, comment='変更後の契約状態'),
    sa.Column('old_end_date', sa.Date(), nullable=True, comment='変更前の終了日'),
    sa.Column('new_end_date', sa.Date(), nullable=True, comment='変更後の終了日'),
    sa.Column('old_monthly_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='変更前の月額料金'),
    sa.Column('new_monthly_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='変更後の月額料金'),
    sa.Column('change_reason', sa.Text(), nullable=True, comment='変更理由'),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False, comment='変更日時'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['company_service_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_subscription_history_changed_by_user_id'), 'service_subscription_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_service_subscription_history_id'), 'service_subscription_history', ['id'], unique=False)
    op.create_index(op.f('ix_service_subscription_history_subscription_id'), 'service_subscription_history', ['subscription_id'], unique=False)
    op.create_table('user_branch_assignments',
    sa.Column('id', sa.Integer(), nullable=False, comment='所属ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('branch_id', sa.Integer(), nullable=False, comment='支店ID'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='主たる所属か'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_branch_assignments_branch_id'), 'user_branch_assignments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_user_branch_assignments_id'), 'user_branch_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_user_branch_assignments_user_id'), 'user_branch_assignments', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False, comment='コメントID'),
    sa.Column('daily_report_id', sa.Integer(), nullable=False, comment='日報ID'),
    sa.Column('commenter_id', sa.Integer(), nullable=False, comment='コメント者ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='コメント内容'),
    sa.Column('commented_at', sa.DateTime(timezone=True), nullable=False, comment='コメント日時'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['commenter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_commenter_id'), 'comments', ['commenter_id'], unique=False)
    op.create_index(op.f('ix_comments_daily_report_id'), 'comments', ['daily_report_id'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False, comment='計画ID'),
    sa.Column('daily_report_id', sa.Integer(), nullable=False, comment='日報ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='計画内容'),
    sa.Column('priority', sa.String(length=50), nullable=True, comment='優先度'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_daily_report_id'), 'plans', ['daily_report_id'], unique=False)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False, comment='課題ID'),
    sa.Column('daily_report_id', sa.Integer(), nullable=False, comment='日報ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='課題内容'),
    sa.Column('priority', sa.String(length=50), nullable=True, comment='優先度'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='ステータス'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_daily_report_id'), 'problems', ['daily_report_id'], unique=False)
    op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    op.create_table('user_department_assignments',
    sa.Column('id', sa.Integer(), nullable=False, comment='所属ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='部署ID'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='主たる所属か'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_department_assignments_department_id'), 'user_department_assignments', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_department_assignments_id'), 'user_department_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_user_department_assignments_user_id'), 'user_department_assignments', ['user_id'], unique=False)
    op.create_table('visit_records',
    sa.Column('id', sa.Integer(), nullable=False, comment='訪問記録ID'),
    sa.Column('daily_report_id', sa.Integer(), nullable=False, comment='日報ID'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='顧客ID'),
    sa.Column('visit_datetime', sa.DateTime(timezone=True), nullable=False, comment='訪問日時'),
    sa.Column('remote', sa.Boolean(), nullable=False, comment='リモート種別 (0:対面 1:リモート)'),
    sa.Column('visit_content', sa.Text(), nullable=True, comment='訪問内容'),
    sa.Column('result', sa.Text(), nullable=True, comment='結果'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_records_customer_id'), 'visit_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_visit_records_daily_report_id'), 'visit_records', ['daily_report_id'], unique=False)
    op.create_index(op.f('ix_visit_records_id'), 'visit_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_records_id'), table_name='visit_records')
    op.drop_index(op.f('ix_visit_records_daily_report_id'), table_name='visit_records')
    op.drop_index(op.f('ix_visit_records_customer_id'), table_name='visit_records')
    op.drop_table('visit_records')
    op.drop_index(op.f('ix_user_department_assignments_user_id'), table_name='user_department_assignments')
    op.drop_index(op.f('ix_user_department_assignments_id'), table_name='user_department_assignments')
    op.drop_index(op.f('ix_user_department_assignments_department_id'), table_name='user_department_assignments')
    op.drop_table('user_department_assignments')
    op.drop_index(op.f('ix_problems_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_daily_report_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_daily_report_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_daily_report_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_commenter_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_user_branch_assignments_user_id'), table_name='user_branch_assignments')
    op.drop_index(op.f('ix_user_branch_assignments_id'), table_name='user_branch_assignments')
    op.drop_index(op.f('ix_user_branch_assignments_branch_id'), table_name='user_branch_assignments')
    op.drop_table('user_branch_assignments')
    op.drop_index(op.f('ix_service_subscription_history_subscription_id'), table_name='service_subscription_history')
    op.drop_index(op.f('ix_service_subscription_history_id'), table_name='service_subscription_history')
    op.drop_index(op.f('ix_service_subscription_history_changed_by_user_id'), table_name='service_subscription_history')
    op.drop_table('service_subscription_history')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_branch_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_daily_reports_user_id'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_report_date'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_id'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_assigned_user_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_company_service_subscriptions_service_id'), table_name='company_service_subscriptions')
    op.drop_index(op.f('ix_company_service_subscriptions_id'), table_name='company_service_subscriptions')
    op.drop_index(op.f('ix_company_service_subscriptions_company_id'), table_name='company_service_subscriptions')
    op.drop_table('company_service_subscriptions')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_services_service_code'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
