"""Add Facility and FacilityAssignment tables

Revision ID: fb17130d1b02
Revises: b81e7a91fd55
Create Date: 2026-01-01 09:42:04.187846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb17130d1b02'
down_revision: Union[str, None] = 'b81e7a91fd55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False, comment='施設ID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='所属企業ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='施設名'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='住所'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='電話番号'),
    sa.Column('description', sa.Text(), nullable=True, comment='説明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_company_id'), 'facilities', ['company_id'], unique=False)
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    op.create_table('facility_assignments',
    sa.Column('id', sa.Integer(), nullable=False, comment='所属ID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='企業ID'),
    sa.Column('facility_id', sa.Integer(), nullable=False, comment='施設ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('contract_type', sa.String(length=50), nullable=False, comment='契約形態（正社員、契約社員、派遣、業務委託など）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id', 'user_id', name='uq_facility_user')
    )
    op.create_index(op.f('ix_facility_assignments_company_id'), 'facility_assignments', ['company_id'], unique=False)
    op.create_index(op.f('ix_facility_assignments_facility_id'), 'facility_assignments', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facility_assignments_id'), 'facility_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_facility_assignments_user_id'), 'facility_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_assignments_user_id'), table_name='facility_assignments')
    op.drop_index(op.f('ix_facility_assignments_id'), table_name='facility_assignments')
    op.drop_index(op.f('ix_facility_assignments_facility_id'), table_name='facility_assignments')
    op.drop_index(op.f('ix_facility_assignments_company_id'), table_name='facility_assignments')
    op.drop_table('facility_assignments')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_company_id'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
